version: "3"

services:
    client:
        build:
            context: .
            dockerfile: Dockerfile
        # ports:
        # - '3000:3000'
        expose:
        - '3000'
        restart: always
        environment: 
            VIRTUAL_HOST: audiopirtis.lt, www.audiopirtis.lt

networks:
  default:
    external:
      name: nginx-proxy